### ISSUE TITLE
Deprecated selector in `cs-slate-syntax/index.less`

### ISSUE THREAD

**Issue by threepointone** [brukh/cs-slate-syntax#1]
In `cs-slate-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.comment` => `.syntax--comment`

* `.entity` => `.syntax--entity`

* `.entity.name.type.class` => `.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.keyword` => `.syntax--keyword`

* `.storage.type` => `.syntax--storage.syntax--type`

* `.storage.modifier` => `.syntax--storage.syntax--modifier`

* `.constant` => `.syntax--constant`

* `.constant.numeric,
.constant.boolean` => `.syntax--constant.syntax--numeric,
.syntax--constant.syntax--boolean`

* `.variable` => `.syntax--variable`

* `.delimiter,
.brace` => `.syntax--delimiter,
.syntax--brace`

* `.delimiter.period` => `.syntax--delimiter.syntax--period`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.string` => `.syntax--string`

* `.string .constant.character.escape` => `.syntax--string .syntax--constant.syntax--character.syntax--escape`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded,
.string.regexp .string.regexp.arbitrary-repitition` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded,
.syntax--string.syntax--regexp .syntax--string.syntax--regexp.syntax--arbitrary-repitition`

* `.keyword.other.phpdoc` => `.syntax--keyword.syntax--other.syntax--phpdoc`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by threepointone** [comment]
(copy pasted from atom)

**Comment by brukh** [comment]
Thanks Sunil, I'll update these today. And sorry for the late response, Houston has been hit with flooding these past few days and I just got back to my computer!

**Comment by threepointone** [comment]
Holy shit I didn't realise you're around there. Take care yo, don't worry about this. Be safe, wish you strength and luck!

**Comment by brukh** [comment]
Thanks man! I am safe now and thankfully my house avoided flooding 🙏🏽 But I just published a new version. Thanks for opening the issue 👍🏽

**Comment by threepointone** [comment]
Glad to hear it. And thank you!
